actorcloud:
  language: zh  # system language: en, zh
  timezone: UTC # system timezone
  log_level: debug  # log level: debug, info, error
  log_path: /logs  # log store path
  actorcloud_api: /api/v1  # api version
  backend_node: 0.0.0.0:7000  # backend server ip:port
  async_tasks_node: 0.0.0.0:7001  # async task node
  codec_node: 0.0.0.0:7002  # codec node
  secret_key: actorcloud9i&jw#$n4yu#n3#c5S7Knn^23ZN  # flask secret key  32 < len < 64
  admin_email: admin@actorcloud.io  # super administrator login username
  admin_password: public  # super administrator login password
  site_name: ActorCloud  # the site name
  site_domain: http://localhost # the site site domain
  email_title: ActorCloud registration invitation # invitation registration email title
  default_devices_limit: -1  # number of devices that tenant can manage. no limit is -1


postgres:
  postgres_host: 192.168.10.131
  postgres_port: 5432
  postgres_user: actorcloud
  postgres_password: public
  postgres_database: actorcloud


emqx:
  emqx_api_version: /api/v4
  emqx_app_id: actorcloud  # emqx application AppID
  emqx_app_secret: Mjk1OTU3Mzg1NDM2ODM4Nzc0MzAzMzE3NDI0MDUzOTQ0MzC # emqx application AppSecret
  emqx_lb_ip: 192.168.10.131  # cluster LB ip. if there is no cluster, it is emqx node ip
  emqx_lb_port: 8081  # emqx http lb api port, the default is 8080
  emqx_nodes:
    # emqx node1 internal ip
    - username: root
      ip: 127.0.0.1
      port: 22

mail:
  mail_server: ''  # smtp server
  mail_port: ''  # smtp server port
  mail_use_ssl: false  # whether to use ssl
  mail_use_tls: true  # whether to use tls
  mail_username: ''  # email username
  mail_password: ''  # email password
  mail_default_sender: ''  # default sender


stream:
  stream_ip: 127.0.0.1  # pulsar ip
  stream_port: 8888  # pulsar port